// ============================================
// MOVIE ROULETTE - CONSTANTS
// ============================================

import type { Language } from './types';

export const STORAGE_KEYS = {
  movies: 'mr_movies',
  tvShows: 'mr_tv',
  backlog: 'mr_backlog',
  watched: 'mr_watched',
  blacklist: 'mr_blacklist',
  tmdbKey: 'mr_key',
  language: 'mr_lang',
  sound: 'mr_sound',
  winCount: 'mr_wins',
} as const;

export const GENRES: Record<number, string> = {
  28: 'Action',
  12: 'Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  14: 'Fantasy',
  36: 'History',
  27: 'Horror',
  10402: 'Music',
  9648: 'Mystery',
  10749: 'Romance',
  878: 'Sci-Fi',
  10770: 'TV Movie',
  53: 'Thriller',
  10752: 'War',
  37: 'Western',
  10759: 'Action & Adv',
  10762: 'Kids',
  10763: 'News',
  10764: 'Reality',
  10765: 'Sci-Fi & Fantasy',
  10766: 'Soap',
  10767: 'Talk',
  10768: 'War & Politics',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'en-US': {
    TITLE: 'MOVIE ROULETTE',
    SUBTITLE: 'What the hell should I watch tonight?',
    NAV_HOME: 'HOME',
    NAV_WATCHLIST: 'WATCHLIST',
    NAV_DISCOVER: 'DISCOVER',
    NAV_SWIPE: 'SWIPE',
    NAV_HISTORY: 'HISTORY',
    NAV_SETTINGS: 'SETTINGS',
    PLACEHOLDER_MOVIES: 'ADD MOVIE...',
    PLACEHOLDER_TV: 'ADD TV SHOW...',
    SPIN_BTN: 'SPIN THE WHEEL',
    SPINNING: 'SPINNING...',
    WINNER_MOVIE: 'MOVIE NIGHT',
    WINNER_TV: 'TV NIGHT',
    BTN_WATCHED: 'WATCHED',
    BTN_TRAILER: 'TRAILER',
    BTN_PROVIDERS: 'STREAMING',
    RATE_TITLE: 'RATING',
    RATE_5: 'EXCELLENT',
    RATE_4: 'GOOD',
    RATE_3: 'OKAY',
    RATE_2: 'BAD',
    RATE_1: 'TERRIBLE',
    RATE_SKIP: 'SKIP RATING',
    DISCOVER_LOCKED: 'Rate 3 items to unlock!',
    DISCOVER_EMPTY: 'Finding matches...',
    BTN_LOAD_MORE: 'LOAD MORE',
    DISC_TOP: 'TOP MATCHES',
    DISC_NEW: 'NEWEST',
    DISC_SOON: 'SOON',
    DISC_GENRE: 'GENRE',
    SWIPE_TITLE: 'THE DECK',
    SWIPE_EMPTY: 'No more cards! Try changing filters or check back later.',
    STATS_TOTAL: 'WATCHED',
    STATS_GENRE: 'FAV GENRE',
    STATS_RATING: 'AVG SCORE',
    TOAST_ADDED: 'Added',
    TOAST_ADDED_WATCHLIST: 'Added to Watchlist',
    TOAST_EXIST: 'Already in list',
    BTN_SEEN: 'SEEN IT',
    UNKNOWN_YEAR: 'Unknown Year',
    NO_PLOT: 'No plot.',
    HEADER_MOVIES: 'YOUR LIST',
    FILTERS: 'FILTERS',
    FILTER_TIME: 'RUNTIME',
    FILTER_GENRE: 'GENRE',
    TIME_SHORT: 'Short (< 90m)',
    TIME_MED: 'Medium (90-120m)',
    TIME_LONG: 'Long (> 2h)',
    EMPTY_LIST: 'Add items to start',
    SETTINGS_TITLE: 'SETTINGS',
    SETTINGS_LANG_LABEL: 'LANGUAGE',
    SOUND: 'SOUND',
    SETTINGS_API_LABEL: 'TMDB API KEY',
    IMPORT: 'IMPORT DATA',
    EXPORT: 'EXPORT DATA',
    TOGGLE_MOVIES: 'MOVIES',
    TOGGLE_TV: 'TV SHOWS',
    RATE_LABEL_ADD: 'RATE',
    DISC_PICK: 'PICK OF THE DAY',
    BTN_CLEAR_MOVIES: 'CLEAR MOVIES',
    BTN_CLEAR_TV: 'CLEAR TV SHOWS',
    DANGER_ZONE: 'DANGER ZONE',
    CONFIRM_CLEAR: 'Are you sure?',
    BTN_ADD_WATCHLIST: 'WATCHLIST',
    HEADER_WATCHLIST: 'WATCHLIST',
    EMPTY_WATCHLIST: 'Your watchlist is empty.',
    BTN_MOVE_TO_ROULETTE: 'MOVE TO ROULETTE',
    HEADER_HIST_MOVIES: 'WATCHED MOVIES',
    HEADER_HIST_TV: 'WATCHED TV SHOWS',
    HEADER_SEEN: 'ALREADY SEEN',
    EMPTY_SEEN: 'No items marked as seen.',
    HIST_TAB_SPINS: 'ROULETTE WINS',
    HIST_TAB_SEEN: 'IMPORTED / SEEN',
    DISC_TAB_MOVIES: 'MOVIES',
    DISC_TAB_TV: 'TV SHOWS',
    MORE_LIKE_THIS: 'MORE LIKE THIS',
    BTN_HIDE: 'HIDE',
    SORT_ADDED: 'DATE ADDED',
    SORT_RELEASE_NEW: 'RELEASE (NEW)',
    SORT_RELEASE_OLD: 'RELEASE (OLD)',
    SORT_RATING: 'HIGH RATING',
    SORT_RUNTIME: 'SHORTEST',
    SORT_ALPHA: 'A-Z',
    SYNC_DATA: 'SYNC METADATA',
    SYNC_DESC: 'Fetch Cast/Director for old items',
    TOP_ACTORS: 'TOP ACTORS',
    TOP_DIRECTORS: 'TOP DIRECTORS',
    FILTER_SOURCE_ALL: 'ALL SOURCES',
    FILTER_SOURCE_ROULETTE: 'ROULETTE WINS',
    FILTER_SOURCE_SEEN: 'MANUAL ENTRY',
    CURATOR_TITLE: "CURATOR'S CHOICE",
    CURATOR_SUB: 'Because you loved',
    ANTI_RUT: 'ANTI-RUT MODE',
    FIRST_SPIN: 'FIRST SPIN!',
    DATE_NIGHT: 'DATE NIGHT',
    BECAUSE: 'Like',
  },
  'pt-PT': {
    TITLE: 'MOVIE ROULETTE',
    SUBTITLE: 'O que devo assistir?',
    NAV_HOME: 'INÍCIO',
    NAV_WATCHLIST: 'VER DEPOIS',
    NAV_DISCOVER: 'DESCOBRIR',
    NAV_SWIPE: 'SWIPE',
    NAV_HISTORY: 'HISTÓRICO',
    NAV_SETTINGS: 'OPÇÕES',
    PLACEHOLDER_MOVIES: 'ADD FILME...',
    PLACEHOLDER_TV: 'ADD SÉRIE...',
    SPIN_BTN: 'GIRAR A RODA',
    SPINNING: 'GIRANDO...',
    WINNER_MOVIE: 'FILME',
    WINNER_TV: 'SÉRIE',
    BTN_WATCHED: 'JÁ VI',
    BTN_TRAILER: 'TRAILER',
    BTN_PROVIDERS: 'ASSISTIR',
    RATE_TITLE: 'AVALIAÇÃO',
    RATE_5: 'EXCELENTE',
    RATE_4: 'BOM',
    RATE_3: 'OK',
    RATE_2: 'MAU',
    RATE_1: 'TERRÍVEL',
    RATE_SKIP: 'PULAR',
    DISCOVER_LOCKED: 'Avalie 3 itens para liberar!',
    DISCOVER_EMPTY: 'Procurando...',
    BTN_LOAD_MORE: 'CARREGAR MAIS',
    DISC_TOP: 'TOPS',
    DISC_NEW: 'RECENTES',
    DISC_SOON: 'BREVE',
    DISC_GENRE: 'GÉNERO',
    SWIPE_TITLE: 'O BARALHO',
    SWIPE_EMPTY: 'Sem mais cartas. Tente mais tarde.',
    STATS_TOTAL: 'VISTOS',
    STATS_GENRE: 'GÉNERO FAV',
    STATS_RATING: 'MÉDIA',
    TOAST_ADDED: 'Adicionado',
    TOAST_ADDED_WATCHLIST: 'Guardado para depois',
    TOAST_EXIST: 'Já na lista',
    BTN_SEEN: 'JÁ VI',
    UNKNOWN_YEAR: 'Ano Desconhecido',
    NO_PLOT: 'Sem descrição.',
    HEADER_MOVIES: 'SUA LISTA',
    FILTERS: 'FILTROS',
    FILTER_TIME: 'DURAÇÃO',
    FILTER_GENRE: 'GÉNERO',
    TIME_SHORT: 'Curto (< 90m)',
    TIME_MED: 'Médio (90-120m)',
    TIME_LONG: 'Longo (> 2h)',
    EMPTY_LIST: 'Adicione itens para começar',
    SETTINGS_TITLE: 'DEFINIÇÕES',
    SETTINGS_LANG_LABEL: 'IDIOMA',
    SOUND: 'SOM',
    SETTINGS_API_LABEL: 'CHAVE API TMDB',
    IMPORT: 'IMPORTAR DADOS',
    EXPORT: 'EXPORTAR DADOS',
    TOGGLE_MOVIES: 'FILMES',
    TOGGLE_TV: 'SÉRIES',
    RATE_LABEL_ADD: 'AVALIAR',
    DISC_PICK: 'DESTAQUE',
    BTN_CLEAR_MOVIES: 'LIMPAR FILMES',
    BTN_CLEAR_TV: 'LIMPAR SÉRIES',
    DANGER_ZONE: 'ZONA DE PERIGO',
    CONFIRM_CLEAR: 'Tem a certeza?',
    BTN_ADD_WATCHLIST: 'VER DEPOIS',
    HEADER_WATCHLIST: 'O COFRE',
    EMPTY_WATCHLIST: 'O cofre está vazio.',
    BTN_MOVE_TO_ROULETTE: 'MOVER PARA ROLETA',
    HEADER_HIST_MOVIES: 'FILMES VISTOS',
    HEADER_HIST_TV: 'SÉRIES VISTAS',
    HEADER_SEEN: 'JÁ VISTOS',
    EMPTY_SEEN: 'Nenhum item marcado.',
    HIST_TAB_SPINS: 'ROLETA',
    HIST_TAB_SEEN: 'JÁ VISTOS',
    DISC_TAB_MOVIES: 'FILMES',
    DISC_TAB_TV: 'SÉRIES',
    MORE_LIKE_THIS: 'RELACIONADOS',
    BTN_HIDE: 'ESCONDER',
    SORT_ADDED: 'DATA (RECENTE)',
    SORT_RELEASE_NEW: 'ANO (NOVO)',
    SORT_RELEASE_OLD: 'ANO (VELHO)',
    SORT_RATING: 'MELHOR NOTA',
    SORT_RUNTIME: 'CURTOS',
    SORT_ALPHA: 'A-Z',
    SYNC_DATA: 'SINCRONIZAR',
    SYNC_DESC: 'Buscar Atores/Diretores para antigos',
    TOP_ACTORS: 'ATORES FAV',
    TOP_DIRECTORS: 'REALIZADORES',
    FILTER_SOURCE_ALL: 'TODAS FONTES',
    FILTER_SOURCE_ROULETTE: 'ROLETA',
    FILTER_SOURCE_SEEN: 'MANUAL',
    CURATOR_TITLE: 'ESCOLHA DO CURADOR',
    CURATOR_SUB: 'Porque gostou de',
    ANTI_RUT: 'MODO ANTI-ROTINA',
    FIRST_SPIN: 'PRIMEIRA!',
    DATE_NIGHT: 'ENCONTRO',
    BECAUSE: 'Tipo',
  },
};

// Date Night Filter Preset
export const DATE_NIGHT_GENRES = [10749, 35, 27]; // Romance, Comedy, Horror
export const DATE_NIGHT_TIME: 'medium' = 'medium';

// API Configuration
export const TMDB_BASE_URL = 'https://api.themoviedb.org/3';
export const TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p';

// Timing Constants
export const SPIN_DURATION_MS = 2500;
export const CONFETTI_DURATION_MS = 4000;
export const TOAST_DURATION_MS = 3000;
export const DEBOUNCE_DELAY_MS = 500;
export const SEARCH_DEBOUNCE_MS = 400;

// Limits
export const SEARCH_RESULTS_LIMIT = 5;
export const TOP_MATCHES_LIMIT = 10;
export const CAST_LIMIT = 6;
export const SIMILAR_LIMIT = 6;
export const POSTER_CACHE_LIMIT = 50;
export const RECOMMENDATION_SEEDS = 5;
